### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by tazitoo**
Changed from listing individual to the "new style" using the admin team

### CODE REVIEW

**Review by ssharpe42 — APPROVED** [review]

**Review by taylorfturner — APPROVED** [review]

**Review by taylorfturner — CHANGES_REQUESTED** [review]
rename team

**Review by taylorfturner — APPROVED** [review]
looks good now

**Comment by taylorfturner** [comment]
Not quite sure why these builds are not even running....

**Comment by ssharpe42** [comment]
> Not quite sure why these builds are not even running....

Maybe close and reopen?

**Comment by taylorfturner** [comment]
> > Not quite sure why these builds are not even running....
> 
> Maybe close and reopen?

We'll give it a go...

**Comment by taylorfturner** [comment]
So perplexed by why these aren't running. Might be worth pushing an empty commit @tazitoo CC @ssharpe42

**Review by taylorfturner — APPROVED** [review]

**Pull request closed without merging**
